name: Release - Reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      npm_install:
        required: true
        type: boolean
    secrets:
      vault_token:
        required: true
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - run: echo npm install
        name: Install NodeJS modules
        if: ${{ inputs.npm_install }}

      - run: echo OK
        name: Release Software

#         if: ${{ startsWith(github.ref, 'refs/tags/') }}
